# Generated by Django 6.0.7 on 2026-07-27 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(help_text='Aparece embaixo do nome da categoria.', max_length=120, verbose_name='Frase curta')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(default='📦', help_text='Um emoji usado como ícone pixelado da categoria.', max_length=8, verbose_name='Ícone (emoji)')),
                ('accent', models.CharField(default='#7CD84A', max_length=7, verbose_name='Cor de destaque (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(max_length=16, verbose_name='Nickname')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Forma de pagamento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total (R$)')),
                ('status', models.CharField(choices=[('PAID', 'Pago'), ('PENDING', 'Pendente')], default='PAID', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=140, verbose_name='Descrição curta')),
                ('description', models.TextField(blank=True, help_text='Uma linha por parágrafo.', verbose_name='Descrição completa')),
                ('perks', models.TextField(blank=True, help_text='Cada linha vira um item da lista de vantagens no card.', verbose_name='Benefícios (um por linha)')),
                ('icon', models.CharField(default='🎁', max_length=8, verbose_name='Ícone (emoji)')),
                ('rarity', models.CharField(choices=[('COMMON', 'Comum'), ('UNCOMMON', 'Incomum'), ('RARE', 'Raro'), ('EPIC', 'Épico'), ('LEGENDARY', 'Lendário')], default='COMMON', max_length=10, verbose_name='Raridade')),
                ('duration_label', models.CharField(blank=True, help_text='Ex.: 30 dias, Permanente, Uso único.', max_length=40, verbose_name='Duração')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido apenas quando o item está em promoção.', max_digits=8, null=True, verbose_name='Preço original (R$)')),
                ('badge_text', models.CharField(blank=True, help_text='Ex.: MAIS VENDIDO, NOVO. Deixe em branco para automático.', max_length=20, verbose_name='Selo personalizado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na home')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Em promoção')),
                ('promotion_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Promoção termina em')),
                ('stock_label', models.CharField(default='Entrega automática', max_length=40, verbose_name='Rótulo de disponibilidade')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('product_icon', models.CharField(default='🎁', max_length=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='OFERTA POR TEMPO LIMITADO', max_length=40, verbose_name='Selo pequeno')),
                ('title', models.CharField(max_length=90, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=160, verbose_name='Subtítulo')),
                ('cta_text', models.CharField(default='Ver oferta', max_length=30, verbose_name='Texto do botão')),
                ('theme', models.CharField(choices=[('forest', 'Floresta / Grass'), ('void', 'Vazio / Espacial'), ('ember', 'Fogo / Energia'), ('aether', 'Místico / Épico')], default='void', max_length=20, verbose_name='Tema visual')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Termina em')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='store.product')),
            ],
            options={
                'verbose_name': 'Banner de promoção',
                'verbose_name_plural': 'Banners de promoção',
                'ordering': ['order'],
            },
        ),
    ]
