# Generated by Django 6.0.7 on 2026-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mascot',
            field=models.CharField(blank=True, help_text='Ex.: img/creatures/creature-vips.svg — criatura pixel art usada como mascote da categoria.', max_length=120, verbose_name='Mascote (caminho estático)'),
        ),
    ]
